service: fortune-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

package:
  include:
    - index.js
    - build/**
    - src/**

functions:
  fortune:
    name: fortune-${self:provider.stage}
    handler: index.handler
    events:
      - http:
          path: /
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - fortune-category
              - fortune-index
              - fortune-offensive
            allowCredentials: false
