service: fortune-lambda

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

package:
  include:
    - index.js
    - src/**
    - messages/**

functions:
  fortune:
    handler: index.handler
    events:
      - http:
          path: index
          method: get
