service: fortune-lambda

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

package:
  include:
    - index.js
    - build/**
    - messages/**
    - src/**

functions:
  fortune:
    name: fortune-${self:provider.stage}
    handler: index.handler
    events:
      - http:
          path: /
          method: get
